-- ============================================================
-- FleetWash OS - REAL ACCOUNT LIST (123 companies)
-- Extracted from your demo (fleetwash-demo-v3) into your live clients table.
--
-- HOW TO RUN:
--   1. Log into the app once (owner profile must exist).
--   2. Supabase -> SQL Editor -> paste this whole file -> RUN.
--   3. Refresh the app -> Accounts tab shows all 123 companies.
--
-- Safe guard: refuses to run if you already have clients, so it
-- cannot create duplicates. To reload, clear clients first.
-- ============================================================

do $$
declare
  v_company uuid;
begin
  select company_id into v_company from profiles where role = 'owner' order by created_at limit 1;
  if v_company is null then
    raise exception 'No owner profile found. Log into the app once, then re-run.';
  end if;
  if (select count(*) from clients where company_id = v_company) > 0 then
    raise exception 'This company already has clients. Clear them before reloading to avoid duplicates.';
  end if;

  insert into clients
    (company_id, name, contact, phone, address, terms, arrival, frequency,
     fleet_notes, specialty, complaints, wash_time, washers, chems, requires_training, kind)
  values
    (v_company, 'A1 Movers', '', '', '704 Banks Ave, Superior, WI 54880', 'Net 30', '', '', 'Varies — tractors, trailers, straight trucks', '', '', '', '', '[]'::jsonb, false, 'client'),
    (v_company, 'Adamich Trucking', '', '', '4202 W Superior St., Duluth, MN', 'Net 30', 'Friday after 4pm', 'Biweekly', '1 tow truck', 'Parks in S&J Truck Repair lot', 'EXTREMELY PICKY!!!', '20 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Agiliti', '', '', '367 Garfield Ave, Duluth, MN 55802', 'Net 30', 'Sunday morning / around Cintas', 'Monthly', '1 box truck, 1 large cargo van', 'Don''t need to wash the smaller cargo van', '', '20 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Airgas - Duluth', '', '', '3102 W Michigan St, Duluth MN', 'Net 30', 'After 3:00 pm on Fridays', 'Bi-weekly', '3 box trucks, 1 cargo van', 'You need a gate key to get into Airgas (garage door opener that opens their gate). They often back up right to the dock but still want the backs done well — maneuver your vehicle to reach these. Usually easiest at the end on the way out.', 'Backs of trucks that are only accessible if you walk up on the dock', '45 min', '2 (need 1)', '[]'::jsonb, false, 'client'),
    (v_company, 'Airgas Hibbing', '', '', '3410 E Beltline Hwy, Hibbing, MN 55746', 'Net 30', '2:00 pm Sundays', 'Bi-weekly', '2-3 box trucks', 'Use the key to enter', 'N/A', '30 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Al Capone Limousine', '', '', '6420 Redruth St', 'Net 30', 'Random', 'As needed (they call)', 'Party buses & limos — no set number ever', 'Kind of weird to get to', 'Very picky! Use lots of water. Windows are biggest overall complaint. Leftover chem trails on vehicle.', 'Random', 'Usually 1', '[]'::jsonb, false, 'client'),
    (v_company, 'Altec', '', '', 'Heritage Center', 'Net 30', 'Random', '', 'Typically 1 aerial boom lift', '', '', '20 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'ATDS', 'Gary', '', '785 Louise Ln NW, Bemidji, MN 56601', 'Net 30', 'Saturdays', 'Weekly', '2-4 tractors, 2-4 trailers', 'They''ll cycle units through the shop so you can wash inside. Knock on shop door and find Gary — you can pull our truck in the shop and he''ll pull trucks in to get washed.', '', '120 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Barr Engineering Duluth', 'Don', '(218) 391-5025', '4503 Airpark Blvd, Duluth MN', 'Net 30', '1:00 pm on Tuesdays', 'Bi-weekly', '5-12 pickup trucks that say Barr on them', 'Call Don 20 minutes before you arrive. Unit numbers are long and in a yellow box generally.', 'Mudflaps, tires, windows', '40 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Beaudry Oil & Propane Bemidji', '', '', '1981 Adams Ave NW, Bemidji, MN 56601', 'Net 30', 'Weekends', 'Biweekly', '2 fuel trucks, 1 boom truck', 'Undercarriages every other service', '', '', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Beaudry Oil & Propane Coleraine', '', '', '803 Cole St., Coleraine, MN', 'Net 30', 'Weekends', 'Biweekly', '3 fuel trucks, 1 service truck', 'Undercarriages every other service', '', '', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Bernick''s Duluth', '', '', '4301 W Michigan St, Duluth MN', 'Net 30', '11:00 am on Mondays', 'Bi-weekly', '10-15 tractors, 10-15 trailers, 5-8 box trucks, 6-10 smaller vehicles (~35 total units)', 'Anything with a Bernick''s logo on it can be washed. Parked on all sides of the building; smaller vehicles can be in the employee lot. Drivers sometimes move them mid-wash — get photos of unit numbers early.', 'Group of 2-3 drivers that complain about small things: windshields, mudflaps/tires, tops of trailers', '300 min', '2 in box, 1 in van toward end', '[]'::jsonb, false, 'client'),
    (v_company, 'Bimbo Bakeries Hibbing', '', '', '2119 MN-37, Hibbing MN', 'Net 30', '10:00 am Wednesdays', 'Bi-weekly', '4-7 box trucks', 'N/A', 'N/A', '60 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Bimbo Bakeries Superior', '', '', '1607 N 6th St, Superior WI', 'Net 30', '11:00 am Wednesdays', 'Bi-weekly', '7-10 box trucks', 'TRICKY — REQUIRES TRAINING (notify management if sent untrained). Door code 1425. Key box code 4132E. Pull trucks ALL the way out to wash, then back them in. Lift gates UP before moving. Keep garage doors shut as much as possible (mice + no wash chems in the building).', 'Mostly concerned about safe driving/backing, keeping trucks straight in spots, liftgates up when moving / down when done', '160 min', '1 (2 makes it ~45 min faster)', '[]'::jsonb, true, 'client'),
    (v_company, 'Bix Produce', '', '', '1301 Garfield Ave, Superior WI', 'Net 30', '10:30 am', 'Bi-weekly', '1-2 box trucks', 'Every other wash they want the backs of the box sprayed out too (specified on schedule)', 'Backs not sprayed out well enough (leftover veggies)', '30 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Blade Companies', 'Luke', '', '5257 Caribou Lake Rd, Saginaw MN', 'Net 30', 'Random — Luke specifies', 'Bi-weekly', '1 tractor, 1 dump truck (changes a lot)', 'We do these at his house — owner operator. Sometimes the address takes you past his driveway (call management with issues).', 'Owner operators are always PICKY! Take your time — he pays well (sometimes tips) and is a great guy', '45 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Border States', '', '', '4451 Airpark Blvd, Duluth, MN 55811', 'Net 30', '5:30 pm on Wednesday', 'Bi-weekly', '2 curtainside box trucks, 1 curtainside trailer, 1 tractor, 1 cargo van', 'UNITS PARKED ON LEFT-HAND SIDE OF LOT. DO NOT GO NEAR FENCED AREA ON RIGHT SIDE — WILL SET OFF MOTION SENSORS', '', '', '', '[]'::jsonb, false, 'client'),
    (v_company, 'Carlson Timber', '', '', 'WLSSD Transfer Station', 'Net 30', '', 'Monthly', 'Material handler, loader, 4 tractors (211, 215, 216, 217 — open hood and wash engine bay), 4 trailers', 'Open panels and wash inside on heavy equipment', '', '', '', '[]'::jsonb, false, 'client'),
    (v_company, 'Charter Spectrum', '', '', '640 Garfield Ave, Duluth MN', 'Net 30', 'Wednesdays 8:00 am', 'Monthly', '~20-25 cargo vans and pickups', 'We wash during their monthly meeting so workers are present and moving. Wash everything that says Charter. COLLECT PLATE NUMBERS!!! Stay until 11 — first wave at the 8am meeting, second wave at 10am.', 'N/A', '~180 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'CHS', 'Cenex Guard Shack', '(218) 341-0595', '41 Dock St, Superior, WI', 'Net 30', 'Saturday @ 9am (1 truck leaves at 10am)', 'Biweekly', '2 tractors, 2 tanker trailers', 'Call the Cenex Guard Shack to be let through the gate — they should know you''re coming. Go right once you enter. Mark down unit #s for trucks (fenders) and trailers (front & back).', '', '', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Cintas Duluth', '', '', '367 Garfield Ave, Superior WI', 'Net 30', 'Varies — parked Friday 5:00 pm through Sunday', 'Weekly', '8-16 box trucks', 'Tough to squeeze in between; fences make the backs hard (do your best). Wash everything that says Cintas. Sometimes film on the sides needs scrubbing even with 2-step.', 'Backs of trucks, buggy windshields, frozen doors (open/close after washing on really cold days)', '180 min', '1, preferably 2', '[]'::jsonb, false, 'client'),
    (v_company, 'Circle K', '', '', '1325 MN-45, Cloquet, MN 55720', 'Net 30', 'Monday @ 5:30 pm', 'Monthly', '4 tractors, 5 trailers', '', '', '', '2', '[]'::jsonb, false, 'client'),
    (v_company, 'Coca-Cola', '', '', '300 S Central Ave, Duluth MN', 'Net 30', '2:00 pm Fridays (arrive before 3 to get let in the gate)', 'Quarterly', '5-8 tractors, 5-8 trailers, 3-5 box trucks. DO NOT WASH PICKUPS OR VANS. 13 units every 4 months.', 'Sometimes you have to go inside and say ''I am here to wash trucks'' to get let in the gate', 'Showing up too late to beat the gate', '180 min', '2', '[]'::jsonb, false, 'client'),
    (v_company, 'Contract Tile & Carpet', '', '', 'Cintas lot', 'Net 30', 'During Cintas wash', 'Biweekly', '1 box truck', 'They bring the box truck over during the Cintas wash. If they don''t show, go down the street and ask when done with Cintas.', '', '', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Country Hearth Bemidji', '', '', '418 Paul Bunyan Dr SE, Bemidji, MN 56601', 'Net 30', 'Saturday at 1:30 pm', 'Bi-weekly', '1 box truck, 2 stepvans', 'They will pull trucks out to hit the backs', '', '', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Country Hearth Duluth', '', '', '43 W Central Entrance, Duluth, MN 55811', 'Net 30', '11:00 am on Wednesdays', 'Bi-weekly', '8-10 box trucks', 'Weird back alley to wash in — do NOT block the alley, don''t let people run over your hose. DO NOT WASH TRACTORS AND TRAILERS.', '', '80 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Country Hearth Grand Rapids', '', '', '3210 SE 6th Ave, Grand Rapids, MN 55744', 'Net 30', 'Saturday after 12 pm, or Sunday', 'Bi-weekly', '3 stepvans', '', '', '', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Dayton Freight', '', '', '3759 Midway Rd, Hermantown', 'Net 30', 'Weekends, no specific time', 'Bi-weekly', '5-7 tractors, 1-3 box trucks. Only wash trailers pulled away from the dock (skip ones against the dock or tucked in the corner).', '', 'Bugs, windows, mudflaps', '90 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Del Zotto Products', '', '', '1900 Co Rd 1, Wrenshall, MN 55797', 'Net 30', 'Weekends', 'Monthly', '2 tractors, 3 trailers, 2 boom trucks', 'They line up the units they want done directly behind the building', '', '', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Demolicious', '', '', '306 S Central Ave, Duluth, MN 55807', 'Net 30', 'Fridays at 3 pm / after Coca-Cola', 'Hook-lifts weekly, tractor monthly', '2 hook-lift trucks, 1 tractor', 'Check in at front desk first. POLISH SAFE ON PETERBILT HOOK-LIFT; REGULAR CHEM ON STERLING HOOK-LIFT & TRACTOR.', '', '', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Dr. Pepper', '', '', '1230 Poplar Ave, Superior, WI', 'Net 30', '9:00 am Sundays', 'Weekly', '5-7 tractors, 5-7 trailers, 4-6 box trucks, 1-2 cars/pickups, 1 dock washout. DO NOT WASH E13036 or B96027.', 'Unit numbers starting with ''M'' are box trucks. ASK MANAGEMENT IF YOU DON''T KNOW WHAT A DOCK WASH IS.', 'Chemical streaking leftover, bugs', '120 min', '1, pref. 2', '[]'::jsonb, false, 'client'),
    (v_company, 'Duluth Tire', '', '', '2802 W Superior St, Duluth, MN 55806', 'Net 30', 'Fridays after Paradis (roughly 4:30)', 'Bi-weekly', '3-4 box trucks, some pickups, rarely a trailer. GO IN AND ASK what they want washed — sometimes nothing.', '', 'Chemical streaking leftover, bugs', '30 min', '1-2', '[]'::jsonb, false, 'client'),
    (v_company, 'Duke Boys Auto', 'Darin', '(218) 391-6097', '6110 Grand Ave, Duluth, MN 55807', 'Net 30', 'Fridays after Demolicious', 'Weekly', '2 Peterbilt tractors, 2 lowboy trailers', 'TAKE BEFORE AND AFTERS TO COVER US. TEXT DARIN 30 MINUTES BEFORE ARRIVAL.', 'VERY PICKY! Complained about mud on tires — wants them scrubbed!', '', '', '[]'::jsonb, false, 'client'),
    (v_company, 'EnviroTech', 'Jamesy (photos)', '', '3200 Winter St, Superior, WI 54880', 'Net 30', '6 pm on Friday', 'Biweekly', '3-4 tractors, 3-4 bulk trailers. Current pairs: 182/483, 185/425, 160/460.', 'Spray bar on the backs of the trailers — they specifically asked for it to be done well (it sprays chemicals onto roads). Lock box code 12345 — key inside unlocks the blue lock. Lock up and RETURN the key when done. TAKE BEFORE/AFTER PHOTOS AND SEND TO JAMESY.', '', '', '1-2', '[]'::jsonb, false, 'client'),
    (v_company, 'Estes Express', '', '', '3302 W 3rd St, Duluth', 'Net 30', 'Random on weekends', 'Every 60 days', '8-15 total: 3-6 tractors, 2 box trucks, 5-6 trailer DOORS only', 'They want only the DOORS on their trailers done — just the back doors on ones pulled away from the dock.', 'Always really gross at 60 days but they expect a high-level wash anyway', '80 min', '1, highly pref. 2', '[]'::jsonb, false, 'client'),
    (v_company, 'FedEx Freight', '', '', '3751 Midway Rd, Hermantown MN', 'Net 30', 'Random, usually mornings (lots of units)', 'As needed', '20-30 total: ~10 tractors, ~10 trailers', 'Only wash trailers pulled away from the docks. Locked gate — we have a key, DON''T forget it at the shop. You MUST lock the gate when you leave (they had an absolute freakout over it once).', 'PICKY — will complain about anything they can', '500 min', '2, pref. 3, ideally 4', '[]'::jsonb, false, 'client'),
    (v_company, 'Ferguson Duluth', '', '', '4209 Airpark Boulevard, Duluth, MN 55811', 'Net 30', 'After 5 pm', 'Biweekly', '8 total: 5 curtain-side box trucks, 2 pickups, 1 cargo van', 'Gate lock code: 2844. WATER RECLAIM. A couple vehicles on the left side of the lot don''t get washed — wash the listed ones parked outside the garages. Close and lock the gate if leaving after 5:00 pm.', 'NEW ACCOUNT — DO AN IMMACULATE JOB! PROVE WE ARE THE BEST!', '60 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Ferrellgas Duluth', '', '', '6049 Rice Lake Rd, Duluth, MN 55803', 'Net 30', 'Wednesday ~5 pm / after Goodin', 'Biweekly', '1 fuel truck', '', '', '15 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Ferrellgas Hibbing', '', '', '11625 US-169, Hibbing, MN', 'Net 30', '3 pm on Wednesday', 'Biweekly', '1 fuel truck', '', 'NEW ACCOUNT — DO AN IMMACULATE JOB! PROVE WE ARE THE BEST!', '', '', '[]'::jsonb, false, 'client'),
    (v_company, 'Fjeran Forest Products', '', '', '1795 HWY 3, Two Harbors MN', 'Net 30', '9 am on Thursday', 'As-needed', '3 tractors, 6 trailers — inside and outside of frame rails', '', '', '', '', '[]'::jsonb, false, 'client'),
    (v_company, 'Goodin Company', '', '', '4524 Venture Ave, Duluth MN', 'Net 30', 'Between 3:00 and 4:00 pm', 'Bi-weekly', '3-7 box trucks', 'Only wash box trucks here. Gate closes at 5:00 pm — be out before then.', 'Bugs, mudflaps, back doors', '80 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'GPM', '', '', '4432 Venture Ave, Duluth MN', 'Net 30', 'After Goodin', 'On-call', '1 flatbed trailer, 1 pickup', 'BRING CTC. Pickup & trailer will be behind or next to the large blue building.', 'Iron ore dust', '', '', '[]'::jsonb, false, 'client'),
    (v_company, 'Graybar Duluth', '', '', '2601 W Superior St', 'Net 30', '12:30 pm on Fridays', 'Bi-weekly', '2-3 box trucks, 1-2 cargo vans', 'The gate is only open between 12:30 and 2:00 to wash the trucks. DO NOT WASH PENSKE RENTAL TRUCKS.', 'Bugs', '60 min', '1, pref. 2', '[]'::jsonb, false, 'client'),
    (v_company, 'Graybar Hibbing', '', '', '3404 15th Ave E #3, Hibbing, MN 55746', 'Net 30', '4:00 pm', 'Bi-weekly', '1 box truck, 1 cargo van', '', 'Leftover chemical staining', '20 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Groome Transportation', '', '', '214 N 34th Ave W, Duluth, MN 55807', 'Net 30', 'Thursdays at 4:30 pm', 'Weekly', 'Up to 15 vans', '', '', '60 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Hartel''s', '', '', '930 U.S. Rte 2, Proctor, MN 55810', 'Net 30', 'Between 1:30 and 3:00 pm, Monday-Thursday', 'Every day', 'Garbage trucks (mark everything as garbage trucks unless it''s the tractor trailer)', 'They line up 6 vehicles for you. Video explainer link lives on the schedule doc.', 'General dirtiness', '90 min', '2', '[]'::jsonb, false, 'client'),
    (v_company, 'Hank''s', 'Noel', '(218) 740-4323', 'Heritage Center', 'Net 30', 'Mondays at 10:20 am', 'Biweekly', 'One box truck', 'Park like you would for Paradis, in the corner of the lot. CALL NOEL WHEN YOU ARRIVE at the Heritage lot.', '', '14 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Hom Furniture', '', '', '4726 Loberg Ave, Hermantown, MN 55811', 'Net 30', '12:30 pm on Mondays', 'Bi-weekly', '4-5 box trucks, 1 cargo van, 1 minivan', '', '', '70 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Hunke''s Transfer', '', '', '1415 Naylor Dr SE, Bemidji, MN 56601', 'Net 30', 'Saturdays, same time as Viking Bemidji', 'Bi-weekly', '1 tractor, 1 trailer, 2 straight trucks', '', '', '60 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Hunt Electric', '', '', '4330 W First St', 'Net 30', '1:30 pm — has to be before 3:00 pm', 'Bi-weekly', '1 lift truck, 2 pickups', 'Go inside and ask what they want done today — anywhere from zero to three units', '', '30 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Jact''s Express', '', '', '514 South Ave, Carlton, MN 55718', 'Net 30', 'Any time Saturdays', 'Bi-weekly', '7-8 tractors', 'DO NOT wash unit numbers 59 & 46', 'Super picky — bugs, mirrors, chemical leftover, mudflaps. We''ve heard it ALL; we often scrub the whole vehicle to avoid complaints.', '90 min', '1, pref. 2', '[]'::jsonb, false, 'client'),
    (v_company, 'JMS Dirt Workx', '', '', '8564 Hwy 37, Iron Junction, MN 55751', 'Net 30', 'Sunday', 'Biweekly', '2-3 units — dump trucks, tractors, trailers', '', '', '', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'John Hashey', 'John', '(715) 919-8046', '4202 W Superior St., Duluth, MN', 'Net 30', 'Friday evenings / with Adamich Trucking', 'Monthly', '1 tractor', 'Sometimes he isn''t there — call John', '', '', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Johnson Brothers', '', '', 'Kivi Bros Lot — 5739 Old Hwy 61, Duluth, MN 55810', 'Net 30', 'Monday @ 9 am', 'Monthly', '8 tractors, 8 trailers', '', '', '100 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Johnson Carpet One', '', '', '1730 W Michigan St, Duluth, MN', 'Net 30', 'Monday afternoon', 'Monthly', '2 newer box trucks. DO NOT WASH THE OLD BOX TRUCK OFF TO THE SIDE.', '', '', '', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Johnson Mertz', '', '', '4258 Haines Rd', 'Net 30', 'Weekend or Friday night', 'Bi-weekly', '2-4 box trucks, 1-2 pickups', 'Prime Appliance is the same as Johnson Mertz', '', '70 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'KCM Trucking', '', '', '414 South Ave, Carlton, MN 55718', 'Net 30', 'Weekends', 'Bi-weekly', '3-5 tractors', '', 'Buggy windshields', '45 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Kimmes Oil', '', '', 'See pin on schedule (maps link)', 'Net 30', 'Weekends, time doesn''t matter', '', '3-5 oil tankers', 'Only wash the tankers — no dump trucks or anything else. Gate CODE: 9634. DO NOT FORGET TO PUT KEY BACK AND LOCK GATE. DO NOT WASH K03 or K02.', '', '60 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Kwik Trip', '', '', '1425 Oakes Ave, Superior, WI 54880', 'Net 30', 'Tuesdays MUST arrive by 1:30 pm (DO NOT BE LATE); Wednesdays after 3:00 pm, usually 4', 'Every Tuesday + every other Wednesday', 'Tuesdays: 3-4 tractors + 3-4 tanker trailers (separate unit #s). Wednesdays: ONLY tractors with box trailers attached (NEVER wash box trailers), 6-8 tractors — don''t forget the tractor wheels under the trailers.', 'GATE ACCESS CODE 45059#. DO UNIT PAIR 242077 & 21102 FIRST ON TUESDAYS (Trent will complain if he''s not first and done fast). UNPLUG TRUCKS BEFORE WASH, REPLUG AFTER. Arrive no later than 1:30 Tuesdays — drivers will be waiting.', 'Being even a minute late on Tuesdays; Wednesday drivers are overall picky', 'Tue 80 min / Wed 70 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Lohse Transfer', '', '', '7 Progress Drive, Esko, MN', 'Net 30', 'Weekends, no specific time', 'Biweekly', '10-13 tractors, 10-15 trailers, 3-7 box trucks', 'DO NOT wash trailers with orange tape on the front near the wires (hard to see). Only wash units that say Lohse — other companies park here.', 'Chemical streaking on tractors, bugs on box trucks', '500 min', '2, pref. 3', '[]'::jsonb, false, 'client'),
    (v_company, 'LKQ', '', '', '4418 Grand Ave, Duluth, MN 55807', 'Net 30', 'Friday afternoon/evening', 'Biweekly', '2 box trucks', 'NEW ACCOUNT — TAKE YOUR TIME AND DO A GREAT JOB', '', '30 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Magnum LTL', '', '', '406 South Ave, Carlton, MN 55718', 'Net 30', 'Weekends, no specific time', 'Monthly', '5-7 tractors, 3-5 trailers, 2-4 box trucks — ONLY wash units on their list (Google Doc on the schedule)', 'Wash only the listed units', '', '240 min', '2', '[]'::jsonb, false, 'client'),
    (v_company, 'MacArthur Co.', '', '', '30 N 43rd Ave W, Duluth, MN 55807', 'Net 30', 'Monday at 8:30 am', 'Biweekly', '1 tractor, 1 cargo van, 1 flatbed pickup (Ford), 1 trailer only if requested', '', '', '', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Maher Trucking', 'Martin', '', '3482 County Hwy 2, Two Harbors, MN 55616', 'Net 30', 'Friday at 1 pm', 'Biweekly', '2-5 garbage trucks — only wash what''s out front. Martin will usually be there to say what he wants done.', '', '', '', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Manion Foods', '', '', '2614 North 14th St, Superior', 'Net 30', '9:00 am Saturdays or Sundays (owner specifies)', 'As needed', '5-6 refrigerated box trucks', 'Inside AND out wash — spray out the insides of the boxes with water (floors, plus walls if you splatter). Close doors and wash exteriors when done inside.', 'PICKY!!! Take your time here.', '90 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Minneapolis Oxygen Duluth', '', '', '3801 S 38th Ave W, Duluth MN', 'Net 30', 'Fridays after 3:00 pm or anytime weekends', 'Bi-weekly', '2-3 box trucks, 1-2 pickups', 'Do not wash the trailer', '', '45 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Minneapolis Oxygen Hibbing', '', '', '3620 E Beltline, Hibbing, MN 55746', 'Net 30', '2:30 pm on Wednesdays', 'Bi-weekly', '1 box truck', 'PRETREAT WITH CTC TO REMOVE IRON ORE FOR NEXT WASH', '', '20 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'N. Trader Trucking', '', '', '2929 Belknap St, Superior, WI 54880 / gravel lot at Allstate Peterbilt', 'Net 30', 'Saturdays', 'Monthly', '8 tractors — polish-safe chemical', '', '', '', '', '[]'::jsonb, false, 'client'),
    (v_company, 'National Minerals Corporation', '', '', '26325 Industrial Blvd, Cohasset, MN', 'Net 30', 'MUST ARRIVE BY 3:00 PM ON SUNDAYS', 'Biweekly', '5 tractors, 4 trailers, 1 polish-safe trailer (Unit #409)', 'MUST arrive by 3:00 pm at the latest — drivers arrive to have their trucks washed. WE ARE ACID WASHING ONE TRAILER PER VISIT.', 'SUPER PICKY — complaints about fly ash. Make sure drivers are happy before they drive away.', '2-3 hours', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Nels Kimball', '', '', '5457 Morris Thomas Rd, Hermantown, MN 55810', 'Net 30', 'TBD', 'Weekly', '2 tractors, 2 trailers', '', 'Owner operator will be very picky! Will likely need pretreat and brush for first wash.', '', '', '[]'::jsonb, false, 'client'),
    (v_company, 'North Central Door', '', '', '900 Carr Lake Rd SE, Bemidji, MN 56601', 'Net 30', 'TBD', 'TBD', '25 trailers (7-8 curtain-sides). Want test wash on 2 trailers.', '', '', '', '', '[]'::jsonb, false, 'client'),
    (v_company, 'Northern Clearing', '', '', 'See map pin on schedule', 'Net 30', '1 pm on Thursday', 'TBD', '1 tractor, 1 lowboy trailer', 'Truck is on the left when you pull into the big lot', '', '30 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Northdale Oil Bemidji', 'Gerald', '', '785 Louise Ln NW, Bemidji, MN 56601', 'Net 30', 'Saturdays', 'Biweekly', '2 bulk trucks, 2 tractors, 2 trailers', 'POLISH-SAFE CHEMICAL ON THE (3) BLUE TRUCKS', 'Gerald is PICKY! Wants us to scrub the windshields.', '', '', '[]'::jsonb, false, 'client'),
    (v_company, 'Northern Star Co-op', '', '', '1325 MN-45, Cloquet, MN 55720', 'Net 30', 'Monday @ 7 pm', 'Biweekly', '2 fuel trucks', '', '', '', '', '[]'::jsonb, false, 'client'),
    (v_company, 'Northwoods Sodding', 'Todd', '(218) 590-6969', '3688 Midway Rd, Hermantown MN', 'Net 30', '11:00 am on Sundays', 'Bi-weekly in summer, as needed in winter', 'Varies a lot', 'Wash everything in the back row of the parking lot (furthest from the road). MUST CALL TODD WHEN YOU ARRIVE.', 'Extreme PICKINESS', '60 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Old Dominion', '', '', '11 Progress Drive, Esko, MN', 'Net 30', 'Weekends, no specific time', 'Tri-weekly (every three weeks)', '8-12 tractors', 'Do not wash trailers', '', '160 min', '1, pref. 2', '[]'::jsonb, false, 'client'),
    (v_company, 'Omaha Track', '', '', '3305 County Rd A, Superior, WI 54880', 'Net 30', 'TBD', '', 'Weekdays: 10 possum-belly trailers (unit #s say TP) + 3 tractors. Weekends: 8 trailers (unit #s say MWF).', 'Note all unit #s washed. Wash under the back of the trailers. Careful washing near wiring on tractors.', '', '', '', '[]'::jsonb, false, 'client'),
    (v_company, 'Paradis', '', '', '120 South 30th Ave W, Duluth, MN 55806 (Heritage Center)', 'Net 30', 'Mondays by 10:45 am (NO LATER); Fridays by 1:30 pm (NO LATER)', 'Weekly', 'Mondays: 1 tractor + 1 trailer. Fridays: usually 4-5 tractors + 4-5 trailers, there till 3:30 pm.', 'Park in the back corner of the lot, farthest from the Heritage Center front door. Drivers pull up ready for a wash and expect BOTH guys washing on Fridays.', '', 'Mon 25 min / Fri 240 min', 'Mon 1 / Fri 2', '[]'::jsonb, false, 'client'),
    (v_company, 'Performance Foodservice', '', '', 'Multiple locations — see fleet notes', 'Net 30', 'See fleet notes', 'Monthly', 'Duluth: 4-5 tractors, 215 S 37th Ave W, Thursday @ 5pm. Swan River: 2 tractors, 16282 US-2, Saturday @ 8:30am. Bemidji: 2-3 tractors, 7929 Fairgrounds Rd NW, Saturday @ 10:30am (with Northdale). Grand Rapids: 1 tractor, 21754 US-169, weekend.', '', '', '', '', '[]'::jsonb, false, 'client'),
    (v_company, 'Pomp''s Tire Service', '', '', '116 Ogden Ave, Superior WI 54880', 'Net 30', '8 am on Friday', 'Bi-weekly', '5 pickups, 1 delivery truck, 1 mini boom truck, 1 large boom truck', '', '', '90 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Red Bull', 'Ethan', '', '4314 Enterprise Circle, Duluth, MN 55811', 'Net 30', '5:00 pm on Mondays', 'Bi-weekly', '4-6 box trucks', 'Ethan will get the trucks in place for you', '', '60 min', '1, pref. 2', '[]'::jsonb, false, 'client'),
    (v_company, 'Rick Peterson', '', '', 'Scanlon Wood Yard', 'Net 30', '', 'Bi-weekly', 'Pulp loader', 'Pretreat with Surefire in the backpack pump sprayer on heavy grease', '', '', '', '[]'::jsonb, false, 'client'),
    (v_company, 'River City Transport', '', '', '2904 Winter St, Superior, WI 54880', 'Net 30', 'Flexible weekends', 'Bi-weekly', '2 day cabs, 2 trailers (43 ft)', '', '', '60 min', '1, pref. 2', '[]'::jsonb, false, 'client'),
    (v_company, 'Safety-Kleen', '', '', '1302 18th St, Cloquet, MN 55720', 'Net 30', 'Weekends', 'Biweekly', '2 box trucks, 1 fuel truck', 'WATER RECLAIM', '', '', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Saginaw Post Office', '', '', '7027 Saginaw Rd, Saginaw, MN 55779', 'Net 30', '5:30 pm on Thursday', 'Monthly', '5 postal trucks', '', '', '35 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Second Harvest Northland', '', '', '2302 Commonwealth Avenue, Duluth, MN 55808', 'Net 30', '4 pm on Thursday', 'Monthly', '8 box trucks, 1 tractor, 1 trailer', 'They want their lot salted after wash', '', '90 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Shane Kimball', '', '', '7521 Comstock Lake Rd, Cotton, MN 55724', 'Net 30', 'After Hibbing on Wednesday', 'Biweekly', '1 tractor (POLISH SAFE CHEM), 1 trailer', '', '', '30 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Shred N Go', 'Travis', '', 'Summer: 5609 St. Louis River Rd Hermantown + 5670 N Cloquet Rd Duluth. Winter: 425 Banks Ave, Superior WI.', 'Net 30', '10:45 am and 11:15 am on Fridays', 'Bi-weekly', '2 box trucks', 'Summer: trucks are parked at the employees'' houses. Winter: indoors at the Superior location — back up to their garage door and run your hose inside. Travis (main contact) will be there; he''s picky and likes to watch, but the nicest dude ever. He loves when we scrub!', 'Basically owner operators, so PICKY', '60 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Simko', '', '', '1901 N 6th St, Superior, WI 54880', 'Net 30', '10:30 am on Saturday', 'Monthly', '7-10 tractors, 11+ trailers, 2-4 box trucks, heavy equipment — units vary each appointment', 'WASH ONLY WHAT IS PARKED ON THE ROAD. If it''s parked in the yard, DO NOT WASH. Take before/after photos of EVERYTHING here.', 'VERY PICKY! Wants trucks brushed. BRING LADDER TO REACH.', '', '', '[]'::jsonb, false, 'client'),
    (v_company, 'Sisu Trucking', '', '', '204 Crosby Rd, Cloquet, MN 55720', 'Net 30', 'On-call; weekends work well', 'On-call', '1 tractor, 3 trailers', '', 'PICKY — USE SCRUB BRUSH', '', '', '[]'::jsonb, false, 'client'),
    (v_company, 'Slumberland', '', '', '4742 Maple Grove Rd', 'Net 30', '11:30 am on Mondays', 'Bi-weekly', '2 box trucks, 1 van', '', '', '45 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Snap-On', '', '', '2844 WI-105, Superior, WI 54880', 'Net 30', '', 'Bi-weekly', '2 box trucks', '', '', '', '', '[]'::jsonb, false, 'client'),
    (v_company, 'Allstate Peterbilt', '', '', '4110 Airpark Blvd, Duluth, MN 55811', 'Net 30', '9:00 am', 'As needed', 'Dealership lot — new/used Peterbilts', 'SPECIALTY WASH — dealership units, use polish-safe chem, no acid. Bright finishes, take your time.', '', '120 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Barr Hibbing', '', '', 'Hibbing, MN', 'Net 30', 'Tuesday afternoons (Hibbing loop)', 'Bi-weekly', 'Barr pickup trucks', 'Part of the Hibbing run — MN Oxy, Barr, Graybar, FerrellGas, Shane Kimball back to back. Unit numbers in yellow box.', 'Mudflaps, tires, windows', '30 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Beaudry Oil & Propane GR', '', '', 'Grand Rapids, MN', 'Net 30', 'Sundays (GR loop)', 'Bi-weekly', 'Fuel trucks, 1 service truck', 'Undercarriages every other service. Part of the Grand Rapids Sunday run.', '', '60 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Brian Carl - Camper', 'Brian Carl', '', 'Duluth area', 'Net 30', 'By appointment', 'As needed', '1 personal camper/RV', 'Owner’s camper — he calls when he wants it done. Hand-detail level, be gentle on decals.', 'Owner is particular', '60 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'CN (Canadian National)', '', '', 'Duluth, MN', 'Net 30', 'Thursdays 10:00 am', 'As needed', 'Rail-yard service trucks', 'Big rail yard — check in at the gate. Long day, lots of units when they call.', '', '180 min', '1-2', '[]'::jsonb, false, 'client'),
    (v_company, 'CN - Virginia', '', '', 'Virginia, MN', 'Net 30', 'Thursdays 9:00 am (Iron Range)', 'As needed', 'Rail-yard service trucks', 'Iron Range rail yard. 7-hour day when scheduled — pack for a full shift.', '', '420 min', '1-2', '[]'::jsonb, false, 'client'),
    (v_company, 'KCM', '', '', 'Grand Rapids / Iron Range', 'Net 30', 'Weekends (Bemidji/GR loop)', 'Bi-weekly', 'Fleet trucks', 'Sometimes needs mold removal on top of the wash (specified on schedule). Part of the northern run.', '', '90 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Performance Foods - Bemidji', '', '', 'Bemidji, MN', 'Net 30', 'Saturday mornings (Bemidji loop)', 'Bi-weekly', 'Reefer box trucks', 'First stop on the Bemidji Saturday run. Spray out the backs when specified.', '', '60 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Performance Foods Grand Rapids', '', '', 'Grand Rapids, MN', 'Net 30', 'Sundays (GR loop)', 'Bi-weekly', 'Reefer box trucks', 'Part of the Grand Rapids Sunday run.', '', '60 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Performance Foods - Swan River', '', '', 'Swan River, MN', 'Net 30', 'Saturday evening (end of Bemidji loop)', 'As needed', '1-2 reefer box trucks', 'Quick stop at the end of the northern run.', '', '30 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Rihm Kenworth', '', '', 'Duluth, MN', 'Net 30', 'Wed/Fri — drive yourself', 'Weekly', 'Dealership Kenworths', 'DRIVE YOURSELF job (personal vehicle, not a rig). Dealership units — polish-safe chem, no acid, bright finishes. Full-day when it runs.', '', '300 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Our Shop', '', '', '149 Erickson Rd, Esko, MN 55733', 'Net 30', '', '', '— bulk water fill site —', 'The pump is in DOOR 6 (furthest to the right) — the only garage door accessible from outside. Training provided on how to run the pump. Tank fills the moment you press ENTER — make sure BOTH ends of the fire hose are attached and in the tank before entering the amount.', '', '', '', '[]'::jsonb, false, 'client'),
    (v_company, 'Carlton Fire Station', '', '', '100 4th St N, Carlton, MN 55718', 'Net 30', '', '', '— bulk water fill site —', 'Access code: 8888#', '', '', '', '[]'::jsonb, false, 'client'),
    (v_company, 'SWLP Bulk Water Fill Station', '', '', '24th St & Grand Ave, Superior, WI', 'Net 30', '', '', '— bulk water fill site —', 'On the corner of 24th St and Grand Ave in Superior. Access code: 0080 followed by our code 8888.', '', '', '', '[]'::jsonb, false, 'client'),
    (v_company, 'Hibbing Fire Hydrant Fill Station', '', '', 'N Salmi Rd & MN-37, Hibbing, MN', 'Net 30', '', '', '— bulk water fill site —', 'Requires the BLUE 2-inch fire hose (not the white 2.5-inch hoses). Gallons measured instantly — no employee tracking needed. Secure blue hose to hydrant, sink other end deep into the tank, turn on water by twisting the dial LEFT.', '', '', '', '[]'::jsonb, false, 'client'),
    (v_company, 'Hermantown Bulk Water Fill Station', '', '', '5255 Maple Grove Rd, Hermantown, MN', 'Net 30', '', '', '— bulk water fill site —', 'On the WEST side of the Hermantown Historical Society building. PAYMENT REQUIRED every time — request a company card from management first and don''t forget a receipt.', '', '', '', '[]'::jsonb, false, 'client'),
    (v_company, 'TG Carroll', 'Terry Carroll', '', '5587 HWY 2, Duluth MN 55810', 'Net 30', 'No set time', 'As needed', 'Completely random', 'Terry Carroll is the owner and will instruct us on what he wants done', 'Terry is EXTREMELY PICKY!', 'Random', '1, random', '[]'::jsonb, false, 'client'),
    (v_company, 'Thompson Excavating', '', '', '39088 State Hwy 47, Aitkin, MN 56431', 'Net 30', '9 am on Sunday', 'Monthly', '3 tractors, 3 trailers, 2 dump trucks, 3 farm tractors', '', '', '', '', '[]'::jsonb, false, 'client'),
    (v_company, 'Tom Kraemer', '', '', '1689 County Road 61, Carlton MN 55718', 'Net 30', 'No set time', 'As needed', 'Jan 28: 4 pickup trucks, 1 16k-lb forklift', 'Wash inside their heated shop', '', 'Random', '1, random', '[]'::jsonb, false, 'client'),
    (v_company, 'Ulland Brothers', 'Storm (sends unit #s)', '', 'Scanlon Pit (Liberty Pit pin on schedule)', 'Net 30', '9 am on Saturday', 'Biweekly', 'Tractors, trailers, dump trucks — Storm will send unit #s', 'Refill hydrant + hose on site in Scanlon: top of the pit past the radio tower, across from the SE corner of the tarp shed. Liberty Pit has NO refill — fill in Scanlon first!!! Lowboy trailer needs polish-safe chemical.', '', '', '', '[]'::jsonb, false, 'client'),
    (v_company, 'Ulland Brothers Virginia', '', '', '7831 Co Rd 921, Virginia, MN 55792', 'Net 30', '9 am on Sunday', 'Biweekly', 'Random', 'NEW ACCOUNT — TAKE YOUR TIME AND DO A GREAT JOB. Bulk water fill on site. GATE CODE: 8126.', '', 'Random 2-6 man hours', '1-2', '[]'::jsonb, false, 'client'),
    (v_company, 'Van Meter', '', '', '4531 W 1st St, Duluth MN 55807', 'Net 30', 'Between 2:00 and 3:30 pm on Mondays', 'Bi-weekly', '2 box trucks, 1 cargo van', 'They sometimes won''t be parked outside — go in and ask', 'Chemical streaking; complained about bugs on June 1st, 2026', '30 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Viking Electric Bemidji', '', '', '1415 Naylor Dr SE, Bemidji, MN 56601', 'Net 30', 'Saturdays', 'Bi-weekly', '2 box trucks', 'BRING SALT IN WINTER. On cold days, crack the back door open a hair to prevent freezing.', '', '', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Viking Electric Duluth', '', '', '15 South 38th Ave W, Duluth, MN 55807', 'Net 30', '4:00 pm on Fridays', 'Bi-weekly', '3-5 box trucks, 1-2 cargo vans', 'Sometimes they pull the trucks out a little so we can hit the backs', '', '90 min', '1, pref. 2', '[]'::jsonb, false, 'client'),
    (v_company, 'Viking Electric Grand Rapids', '', '', '807 Lily Ln, Grand Rapids, MN 55744', 'Net 30', 'Saturdays or Sundays', 'Bi-weekly', '1 cargo van, 1 box truck', 'BRING SALT. On cold days, crack the back door open a hair to prevent freezing.', '', '', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Walter''s Demolition & Disposal', '', '', '400 Landfill Rd, Hibbing, MN', 'Net 30', '3 pm on Wednesday', 'Twice yearly', '2 aluminum side trailers', 'Bring Surefire & Aluminum Brightener. Back end of trailer has garbage juice — Surefire there, aluminum brightener on the rest.', '', '2 hours', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'Waste Management - Cambridge', '', '', '1505 11th Avenue NE, Cambridge, MN 55008', 'Net 30', '', 'Weekly', '30-38 trucks, mostly garbage trucks', 'NEEDS WATER RECLAIM. Water refill location: 645 Emerson St N, Cambridge — NEED A CREDIT CARD TO REFILL. (Titled ''Cohasset'' in the doc but the address is Cambridge.)', 'NEW ACCOUNT — TAKE YOUR TIME', '400 min', '2', '[]'::jsonb, false, 'client'),
    (v_company, 'Waste Management - Cohasset', '', '', '511 US-2, Cohasset', 'Net 30', '', 'Weekly', '12-18 trucks — mostly garbage trucks, some pickups and a box truck', 'DO NOT WASH HERE WITHOUT PROPER TRAINING. Leave everything exactly as found: same doors locked, same lights on, trucks in same locations. Chalk tires, plug in trucks, main power switches OFF. A driver meets you to pull trucks — PAY HIM $100 at end of wash.', 'Driver of 217457 is very picky! Overall picky fleet. Biggest complaint is frame rails / undercarriage (battery box, DEF tank etc.)', '400 min', '2 washers + 1 driver best; 1 washer + 1 driver fine', '[]'::jsonb, true, 'client'),
    (v_company, 'Waste Management - Duluth', '', '', '3101 West Superior St, Duluth MN', 'Net 30', '5:00 pm on Tuesdays', 'Weekly', '30-40 garbage trucks', 'Must reclaim water (contact management for instructions). Mechanics move trucks in and out of their shop — keep an eye out and move your wash setup as necessary.', 'Backs of cabs, undercarriage, mudflaps, backs of trucks (hard to reach because of fence)', '400 min', '3', '[]'::jsonb, false, 'client'),
    (v_company, 'Twin Ports Paper', 'Jerry', '', '4223 Airpark Blvd, Hermantown MN', 'Net 30', '2:30 pm on Mondays', 'Monthly', '3-5 box trucks', 'They pull them off to the side for you. Go inside and tell Jerry you''re there and ready to wash.', '', '70 min', '1', '[]'::jsonb, false, 'client'),
    (v_company, 'The Mobile Wash Company', '', '', 'Shop', '—', '', '', 'Shop stops, meetings, rig maintenance', 'Internal — shop time, weekly meeting, equipment work.', '', '', '', '[]'::jsonb, false, 'client');

  raise notice 'Loaded % companies for %', (select count(*) from clients where company_id=v_company), v_company;
end $$;
